// Generated by gencpp from file abb_irb120/pos_speed.msg
// DO NOT EDIT!


#ifndef ABB_IRB120_MESSAGE_POS_SPEED_H
#define ABB_IRB120_MESSAGE_POS_SPEED_H

#include <ros/service_traits.h>


#include <abb_irb120/pos_speedRequest.h>
#include <abb_irb120/pos_speedResponse.h>


namespace abb_irb120
{

struct pos_speed
{

typedef pos_speedRequest Request;
typedef pos_speedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct pos_speed
} // namespace abb_irb120


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::abb_irb120::pos_speed > {
  static const char* value()
  {
    return "556fae5da7a1874be33b0b17716aa737";
  }

  static const char* value(const ::abb_irb120::pos_speed&) { return value(); }
};

template<>
struct DataType< ::abb_irb120::pos_speed > {
  static const char* value()
  {
    return "abb_irb120/pos_speed";
  }

  static const char* value(const ::abb_irb120::pos_speed&) { return value(); }
};


// service_traits::MD5Sum< ::abb_irb120::pos_speedRequest> should match 
// service_traits::MD5Sum< ::abb_irb120::pos_speed > 
template<>
struct MD5Sum< ::abb_irb120::pos_speedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::abb_irb120::pos_speed >::value();
  }
  static const char* value(const ::abb_irb120::pos_speedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_irb120::pos_speedRequest> should match 
// service_traits::DataType< ::abb_irb120::pos_speed > 
template<>
struct DataType< ::abb_irb120::pos_speedRequest>
{
  static const char* value()
  {
    return DataType< ::abb_irb120::pos_speed >::value();
  }
  static const char* value(const ::abb_irb120::pos_speedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::abb_irb120::pos_speedResponse> should match 
// service_traits::MD5Sum< ::abb_irb120::pos_speed > 
template<>
struct MD5Sum< ::abb_irb120::pos_speedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::abb_irb120::pos_speed >::value();
  }
  static const char* value(const ::abb_irb120::pos_speedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::abb_irb120::pos_speedResponse> should match 
// service_traits::DataType< ::abb_irb120::pos_speed > 
template<>
struct DataType< ::abb_irb120::pos_speedResponse>
{
  static const char* value()
  {
    return DataType< ::abb_irb120::pos_speed >::value();
  }
  static const char* value(const ::abb_irb120::pos_speedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ABB_IRB120_MESSAGE_POS_SPEED_H
